name: CI Development
on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Ruff Check
      - uses: chartboost/ruff-action@v1
      - name: Run Tests
        run: |
          pip install -r requirements.txt .
          pip install pytest
          pytest -s tests/
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.7.1"
      - name: Configure Poetry
        run: poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - name: Build Poetry
        run: poetry build
      - name: Publish Package
        run: poetry publish --repository test-pypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}